apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: media-memcached
  name: media-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: media-memcached
    spec:
      containers:
        - image: memcached
          name: media-memcached
          ports:
            - containerPort: 11211
          resources: {}
      hostname: media-memcached
      restartPolicy: Always
status: {}
