apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-mongodb
  name: social-graph-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: social-graph-mongodb
    spec:
      containers:
        - args:
            - --config
            - /social-network-microservices/config/mongod.conf
          image: mongo
          name: social-graph-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: social-graph-mongodb-hostpath0
            - mountPath: /keys
              name: social-graph-mongodb-hostpath1
      hostname: social-graph-mongodb
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/yig004/Source/envirocloud/k8s/DeathStarBench/socialNetwork/config
          name: social-graph-mongodb-hostpath0
        - hostPath:
            path: /home/yig004/Source/envirocloud/k8s/DeathStarBench/socialNetwork/keys
          name: social-graph-mongodb-hostpath1
status: {}
