apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: text-service
  name: text-service
spec:
  ports:
    - name: "10007"
      port: 10007
      targetPort: 9090
  selector:
    io.kompose.service: text-service
status:
  loadBalancer: {}
