apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: user-mention-service
  name: user-mention-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-mention-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml --volumes hostPath
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: user-mention-service
    spec:
      containers:
        - command:
            - UserMentionService
          image: registry.k8s.local/dsb/social-network-microservices:latest
          name: user-mention-service
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: user-mention-service-hostpath0
            - mountPath: /keys
              name: user-mention-service-hostpath1
      hostname: user-mention-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/yig004/Source/envirocloud/k8s/DeathStarBench/socialNetwork/config
          name: user-mention-service-hostpath0
        - hostPath:
            path: /home/yig004/Source/envirocloud/k8s/DeathStarBench/socialNetwork/keys
          name: user-mention-service-hostpath1
status: {}
